### ISSUE TITLE
Home Gallery: automatische foto's

### ISSUE THREAD

**Issue by Denperidge** [MaxxxFoxxx/4Claws-Website#8]
Manueel de foto's toevoegen is duizenden keren gemakkelijker dan het automatiseren ervan

Maar dat heeft mij nog nooit gestopt

(Goal: alle foto's van één folder automatisch in de gallerij laden, zodat we gemakkelijk foto's kunnen toevoegen en verwijderen)

**Comment by Denperidge** [comment]
De beste manier (dat ik op het moment weet) is een consistent naamsysteem. Bijvoorbeeld pic1, pic2, pic3... met een for loop in de JS. Ik hoop nog steeds dat ik een betere manier kan vinden, maar geen idee of dat mogelijk is. Indien niet, werkt dit perfect.

**Comment by Denperidge** [comment]
We gaan een compromis moeten houden. Een consistent naamsysteem, maar ik ga een klein exe'tje schrijven voor  het hernoemen te automatiseren, als dat helpt. Nieuwe test branch "gallerij" aangemaakt.

**Comment by MaxxxFoxxx** [comment]
Oke, gonna be honest here, echt geen idee wat een consisten naamsysteem is, als ik het zou weten zou ik het proberen ma idfk
